name: Production - Build and Push to GCP Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Enable experimental docker'
        run: |
          sudo bash -c 'echo "{\"experimental\": true}" > /etc/docker/daemon.json'
          sudo systemctl restart docker

      - name: Checkout
        uses: actions/checkout@v3

      # Configure Workload Identity Federation and generate an access token.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.6.0'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.CODECOV_GCP_WIDP }}
          service_account: ${{ secrets.CODECOV_GCP_WIDSA }}

      - name: Docker configuration
        run: |-
          echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://us-docker.pkg.dev

      # Build the Docker image
      - name: Build
        env:
          ENV: production
          NPM_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        run: |-
          make build

      - name: Build Enterprise
        env:
          ENV: enterprise
          NPM_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        run: |-
          make build.enterprise

      - name: Dive
        env:
          ENV: production
        run: |-
          make dive

      - name: Deep Dive
        run: |-
          make deep-dive

      # Push the Docker image to Google Artifact Registry
      - name: Publish
        env:
          ENV: production
        run: |-
          make push

      - name: Publish Enterprise
        env:
          ENV: enterprise
        run: |-
          make push.enterprise
          
      

  release:
    uses: ./.github/workflows/client-release.yaml
    with:
      bucket: ${{ secrets.bucket_alpha }}
      client_name: ${{ secrets.client_alpha }}
      api_url: ${{ secrets.api_url_alpha }}
      base_url: ${{ secrets.base_url_alpha }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      gcp_sa: ${{ secrets.CODECOV_GCP_WIDSA }}
      gcp_idp: ${{ secrets.CODECOV_GCP_WIDP }}
    permissions:
      pull-requests: 'write'
      contents: 'read'
      id-token: 'write'
      actions: 'read'
      repository-projects: 'read'